version: "3.3"
services:
  api:
    image: ${DMS_ADMIN_IMAGE_REGISTRY:-dms-admin}/backend:${DMS_ADMIN_IMAGE_TAG:-latest}
    environment:
      DMS_ADMIN_ADMIN_USERNAME: ${DMS_ADMIN_ADMIN_USERNAME:-admin}
      DMS_ADMIN_ADMIN_PASSWORD: ${DMS_ADMIN_ADMIN_PASSWORD:-admin}
      DMS_ADMIN_SESSION_SECRET: ${DMS_ADMIN_SESSION_SECRET:-local-dev-secret}
      DMS_ADMIN_DMS_CONTAINER_NAME: ${DMS_ADMIN_DMS_CONTAINER_NAME:-mailserver}
    ports:
      - "${DMS_ADMIN_API_PORT:-8000}:8000"
